### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by darwin67** [markphelps/flipt-grpc-ruby#6]
Hello,

I was trying this grpc client out but seems like you didn't check in the generated `annotations_pb` and it's causing the following errors.

```
❯ be flipt.rb
bundler: failed to load command: flipt.rb (flipt.rb)
LoadError: cannot load such file -- protoc-gen-swagger/options/annotations_pb
  /home/darwin/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/bundler/gems/flipt-grpc-ruby-e06a6eb52f97/lib/flipt_pb.rb:8:in `require'
  /home/darwin/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/bundler/gems/flipt-grpc-ruby-e06a6eb52f97/lib/flipt_pb.rb:8:in `<top (required)>'
  /home/darwin/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/bundler/gems/flipt-grpc-ruby-e06a6eb52f97/lib/flipt_services_pb.rb:5:in `require'
  /home/darwin/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/bundler/gems/flipt-grpc-ruby-e06a6eb52f97/lib/flipt_services_pb.rb:5:in `<top (required)>'
  flipt.rb:4:in `require'
  flipt.rb:4:in `<top (required)>'
```

the example Gemfile also doesn't have a `source` too so perhaps something to fix there as well.
and please exclude the Gemfile.lock since it won't function on a Linux machine.

**Comment by markphelps** [comment]
See #7 

Fixed in v0.4.0
